# Ocean of Opportunities config file
# >> Edit lines below as per your needs >>
title: "Ocean of Opportunities" # Name to show in top left of website and to search engines
description: A Jekyll powered personal portfolio website theme # Site desciption
baseurl: "/Ocean-of-Opportunities" # Path to repository, if using in 'yourname.github.io' repository, change to "" (blank) else put repository name here.
url: "https://kuwushagra.github.io" # URL of your website
author: Kushagra Bhagat # Name of the author, which also appears in the footer
defaultimage: "" # Default banner image that will appear when you share a link to any page on another platform
githublink: https://github.com/yourgithubusername # Link to your GitHub profile
mailaddress: youremailadresshere # Put your e-mail id here
favicons: "/assets/images" # Path to your favicon
footerlink: https://kuwushagra.github.io # Link to other social media or linktree, whatever you wish
headercomponents: # Name and link of pages displayed in header
  - name: "About"
    url: "/about"
  - name: "My Projects"
    url: "/projects"
  - name: "Blog Posts"
    url: "/posts"
fishlinks: # Links the fish open on clicking. You can put as many as you want but links will cycle in batches of 3.
  - "/projects/Project1"
  - "/projects/Project2"
  - "/projects/Project3"
# >> Advanced config below. You need not edit this for basic theme functionality >>
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title.html
# End of config
